# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brightcove/BrightcoveSpecs.git'

target 'Watchback' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Watchback
  pod 'Fabric'
  pod 'Crashlytics'
  
  pod 'Toast', '~> 3.1.0'
  #pod 'OpenUDID', '~> 1.0'
  
  #pod 'Reachability'
  ### PERK
  
  
  ###
  pod 'Brightcove-Player-Core'
  #pod 'Brightcove-Player-FreeWheel'
  
  ####
  pod 'iCarousel', '~> 1.8'
  
  ####
  pod "ComScore"
  
  #####
  pod 'Leanplum-iOS-SDK'
  # pod 'Leanplum-iOS-Location'
  
  ####
  
  pod 'AppsFlyerFramework'
  
  ###
  # pod 'FBSDKLoginKit'
  pod 'FBSDKCoreKit'
  
  ###
  
  pod 'Shimmer', '~> 1.0'
  
  pod 'MBProgressHUD', '~> 1.1'
  pod 'SDWebImage', '~> 5.0'

  
end
#target 'NotificationService' do
#    pod 'OneSignal', '>= 2.5.2', '< 3.0'
#end
